# Generated by Django 5.2.8 on 2025-11-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
    ]
